on:
  push:
    branches:
      - dev

name: Dev Deployment

jobs:
  deploy:
      name: Deploy
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [12.x]
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Copy .env
        uses: c-py/action-dotenv-to-setenv@v1
        with:
          env-file: .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: User Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Login To DockerHub
        uses: docker/login-action@v1
        with: 
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockefile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE_NAME}}:${{env.TAG}}
