on:
  push:
    branches:
      - ci_setup

name: Dev Deployment

jobs:
  deploy:
      name: Deploy
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [12.x]
      steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: User Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get tag
        run: echo ::set-env name=APP_TAG::$(node -e 'console.log(require("./tools/version.js"))' && echo $stdin)
      - name: Login to docker hub
        if: success()
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      
      - name: Building Docker image
        run: docker build -t ${{env.APP_TAG}} .

      - name: Tag Docker image
        run: docker tag ${{env.APP_TAG}} ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE_NAME}}:${{env.APP_TAG}}

      - name: Publishing Docker image
        run: docker push ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE_NAME}}:${{env.APP_TAG}}
